DROP TABLE IF EXISTS familie;

CREATE TABLE familie (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	valoare INTEGER NOT NULL,
	detalii TEXT NOT NULL
);
